/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MyInterface } from "./MyInterface";

export { MyInterface__factory } from "./factories/MyInterface__factory";
